# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - azure-pipelines.yml

stages:
  - stage: Build
    displayName: Build the project
    jobs:
    - job: Build
      displayName: Build job
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: NodeTool@0
          inputs:
            versionSource: 'spec'
            versionSpec: '18.x'
          displayName: 'Install Node.js'
        
        - script: |
            npm install -g aws-cdk
        
        - script: |
            npm install
        
        - script: |
            cdk deploy
