# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - azure-pipelines.
      
pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '18.x'
    displayName: 'Install Node.js'
  
  - script: |
      npm install -g aws-cdk
      npm install --legacy-peer-deps
    displayName: 'Install AWS-CDK and dependencies'

  - task: AWSShellScript@1
    inputs:
      awsCredentials: 'aws'
      regionName: '$(REGION)'
      scriptType: 'inline'
      inlineScript: 'cdk deploy --require-approval never'
      disableAutoCwd: true
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'cdk deploy'
